local FailureReport=require("failure_report")
test("failure reports sanitize sensitive and personal material",function()
  local saved; local reporter=FailureReport.new({version="0.2.146",edition="player",clock=function() return 42 end,save=function(report) saved=report end})
  local report=reporter:record("map_library",'token=secret password=hunter2 user@example.com 10.2.3.4 /Users/gia/private/map.json https://example.test/path?q=secret "Kaida says hello"',{operation="install",stage="download",character_name="Gia",room_count=12}); local message=report.message
  eq(message:find("secret",1,true),nil); eq(message:find("hunter2",1,true),nil); eq(message:find("user@example.com",1,true),nil); eq(message:find("10.2.3.4",1,true),nil); eq(message:find("/Users/",1,true),nil); eq(message:find("Kaida",1,true),nil); eq(report.context.operation,"install"); eq(report.context.room_count,"12"); eq(report.context.character_name,nil); eq(saved,report)
end)
test("failure reports retain only bounded sanitized history",function() local reporter=FailureReport.new({clock=function() return 7 end}); for index=1,25 do reporter:record("map",string.rep("x",600)..index) end; local report=reporter:lastReport(); eq(#report.events,20); eq(#report.message<=503,true); eq(report.format,"DGHUD-failure-report"); eq(report.schema,1) end)
test("anonymous submission is single flight and callback driven",function() local finish; local reporter=FailureReport.new({submit=function(report,done) finish=done; return true end}); local report=reporter:record("map_library","download failed"); assert(reporter:submitReport(report)); local started,err=reporter:submitReport(report); eq(started,nil); eq(err,"failure report submission is already running"); finish({ok=true}); eq(reporter.submitting,false); assert(reporter:submitReport(report)) end)
test("capture and submit preserves the report when transport cannot start",function() local reporter=FailureReport.new({submit=function() return nil,"offline" end}); local report,started,err=reporter:captureAndSubmit("map_library","catalog failed",{operation="browse"}); eq(report.category,"map_library"); eq(started,nil); eq(err,"offline"); eq(reporter.submitting,false) end)
test("failure API exposes only centralized report operations",function()
  local Main=require("main"); local previous=rawget(_G,"DGHUD"); local submitted=false
  local reports=FailureReport.new({submit=function(_,done) submitted=true; done({ok=true}); return true end}); rawset(_G,"DGHUD",{controller={failure_reports=reports,captureFailure=function(_,category,message,context) return reports:captureAndSubmit(category,message,context) end}})
  local namespace={}; local api=Main.installFailureApi(namespace); local report=api.report("map_library","token=private",{operation="install",name="character"}); eq(report.message:find("private",1,true),nil); eq(report.context.name,nil); eq(api.last(),report); assert(api.submitLast()); eq(submitted,true); rawset(_G,"DGHUD",previous)
end)
