local Layout=require("layout")
test("wide screens reserve seventeen percent for each HUD rail",function()
  local r=Layout.compute(1920,1080); eq(r.mode,"wide"); eq(r.left,326); eq(r.right,326); eq(r.console_gutter,10); eq(r.console_left,336); eq(r.console_width,1248); eq(r.header_height,74); eq(r.show_character_rail,true); eq(r.vitals_side,"center")
end)
test("chatbox aligns exactly with center console",function()
  local r=Layout.compute(1920,1080)
  eq(r.chat_x,r.console_left); eq(r.chat_width,r.console_width); eq(r.chat_height,240)
  eq(r.console_top,r.header_height+r.chat_height); eq(r.top,r.console_top)
end)
test("chat height scales and clamps",function()
  eq(Layout.compute(1200,650).chat_height>=160,true)
  eq(Layout.compute(3840,2160).chat_height<=320,true)
end)
test("chat allocation preserves a usable console remainder at medium and compact thresholds",function()
  for _,case in ipairs({{width=1200,header=66},{width=760,header=116}}) do
    local sample=Layout.compute(case.width,700); local threshold=case.header+sample.bottom+160+120
    local above=Layout.compute(case.width,threshold+1); local at=Layout.compute(case.width,threshold); local below=Layout.compute(case.width,threshold-1)
    eq(at.minimum_console_remainder,120)
    eq(above.chat_height,160); eq(above.console_remainder,121)
    eq(at.chat_height,160); eq(at.console_remainder,120)
    eq(below.chat_height,159); eq(below.console_remainder,120)
    eq(below.chat_height>0,true); eq(below.console_top<below.window_height,true)
  end
end)
test("short medium and compact layouts keep chat visible above the console remainder",function()
  local medium=Layout.compute(1200,200); local compact=Layout.compute(760,240)
  eq(medium.chat_height,60); eq(medium.chat_output_height,16); eq(medium.console_remainder,medium.window_height-medium.bottom-medium.console_top)
  eq(compact.chat_height,60); eq(compact.chat_output_height,16); eq(compact.console_remainder,compact.window_height-compact.bottom-compact.console_top)
  eq(medium.console_remainder>0,true); eq(compact.console_remainder>0,true)
  eq(medium.console_top<=medium.window_height,true); eq(compact.console_top<=compact.window_height,true)
end)
test("functional chat chrome floor adapts the console minimum at medium and compact boundaries",function()
  for _,case in ipairs({{width=1200,header=66},{width=760,header=116}}) do
    local sample=Layout.compute(case.width,700); local threshold=case.header+sample.bottom+60+120
    local above=Layout.compute(case.width,threshold+1); local at=Layout.compute(case.width,threshold); local below=Layout.compute(case.width,threshold-1)
    eq(at.chat_functional_minimum,60); eq(at.chat_height,60); eq(at.chat_output_height,16); eq(at.console_remainder,120)
    eq(above.chat_height,61); eq(above.chat_output_height,17); eq(above.console_remainder,120)
    eq(below.chat_height,60); eq(below.chat_output_height,16); eq(below.console_remainder,119)
    eq(below.console_remainder>0,true)
  end
end)
test("extreme compact height compresses header before chat or console overrun",function()
  local r=Layout.compute(760,150)
  eq(r.header_height,56); eq(r.chat_height,60); eq(r.chat_output_height,16); eq(r.console_remainder,1)
  eq(r.console_top<=r.window_height,true)
end)
test("normal layouts retain their breakpoint headers and chat geometry",function()
  local compact=Layout.compute(760,700); local medium=Layout.compute(1200,800); local wide=Layout.compute(1920,1080)
  eq(compact.header_height,116); eq(compact.chat_height,160)
  eq(medium.header_height,66); eq(medium.chat_height,178)
  eq(wide.header_height,74); eq(wide.chat_height,240)
end)
test("chat wrap columns follow the center display width",function()
  local narrow=Layout.compute(1000,700); local wide=Layout.compute(1920,1080)
  eq(narrow.chat_wrap_columns<wide.chat_wrap_columns,true); eq(narrow.chat_wrap_columns>=30,true)
end)
test("chat wrap fallback never claims more columns than its computed width",function()
  local r=Layout.compute(120,500)
  eq(r.chat_wrap_columns,math.max(1,math.floor(r.chat_inner_width/r.chat_character_width)))
  eq(r.chat_wrap_columns<30,true)
end)
test("chat text scales slightly smaller than the surrounding HUD",function()
  eq(Layout.compute(760,700).chat_font,11)
  eq(Layout.compute(1920,1080).chat_font,13)
  eq(Layout.compute(3840,2160).chat_font,15)
end)
test("chat height follows supplied percentage while retaining reference target",function()
  local default=Layout.compute(1920,1080); local taller=Layout.compute(1920,1080,{height_percent=.25})
  eq(default.chat_height,240); eq(taller.chat_height>default.chat_height,true)
end)
test("medium screens preserve the seventeen sixty-six seventeen split",function()
  local r=Layout.compute(1200,800); eq(r.mode,"medium"); eq(r.left,204); eq(r.right,204); eq(r.console_gutter,6); eq(r.console_left,210); eq(r.console_width,780); eq(r.header_height,66); eq(r.show_character_rail,true); eq(r.show_room_compass,true); eq(r.vitals_side,"center")
end)
test("compact screens move all status out of side rails",function()
  local r=Layout.compute(760,700); eq(r.mode,"compact"); eq(r.left,0); eq(r.right,0); eq(r.header_height,116); eq(r.bottom,r.vitals_strip_height+r.command_line_clearance); eq(r.bottom>0,true); eq(r.show_room_compass,false)
end)
test("desktop breakpoint crossings retain rails until genuinely compact widths",function()
  for _,width in ipairs({999,1000,1399,1400}) do
    local r=Layout.compute(width,700)
    eq(r.mode,width>=1400 and "wide" or "medium")
    eq(r.left>0,true); eq(r.right>0,true); eq(r.console_width>0,true)
  end
end)
test("center vitals strip meets the native command line without duplicate clearance",function()
  for _,size in ipairs({{760,700},{1200,800},{2560,1400}}) do local r=Layout.compute(size[1],size[2]); eq(r.bottom,r.vitals_strip_height); eq(r.command_line_clearance,0); eq(r.console_remainder,r.window_height-r.console_top-r.bottom) end
end)
test("console gutter approximates half a percent but caps on wide displays",function()
  for _,case in ipairs({{1920,10},{2560,12},{3840,12},{7680,12}}) do
    local width,expected=case[1],case[2]
    local r=Layout.compute(width,1080)
    eq(r.console_gutter,expected)
    eq(r.console_left,r.left+expected)
    eq(r.console_right,r.right+expected)
    eq(r.console_width,width-r.console_left-r.console_right)
  end
end)
test("layout keeps a usable center console with capped gutters",function()
  for _,w in ipairs({1000,1024,1366,1400,1600,1920,2056,2560,3840,7680}) do
    local r=Layout.compute(w,900)
    eq(r.console_width>=math.floor(w*.65),true)
    eq(r.console_gutter<=12,true)
  end
end)
test("responsive typography remains readable at every breakpoint",function()
  local compact=Layout.compute(760,700); local medium=Layout.compute(1200,800); local wide=Layout.compute(2056,1177); local ultra=Layout.compute(3840,2160)
  eq(compact.body_font>=16,true); eq(medium.body_font>=16,true); eq(wide.body_font>=20,true); eq(ultra.body_font>=22,true)
  eq(wide.heading_font>wide.body_font,true); eq(wide.gauge_height>=26,true); eq(wide.panel_padding>=16,true)
  eq(wide.small_font>=(wide.body_font-2)*2,true); eq(wide.gauge_height>=wide.small_font+10,true)
end)
test("equipment card typography and padding are smaller than standard cards",function()
  for _,size in ipairs({{1000,900},{1920,1080},{3840,2160}}) do
    local r=Layout.compute(size[1],size[2])
    eq(r.equipment_font<r.body_font,true)
    eq(r.equipment_font>=13,true)
    eq(r.equipment_padding<r.panel_padding,true)
  end
end)
test("scrollable list text is three pixels smaller while headings stay readable",function()
  for _,size in ipairs({{1000,900},{1920,1080},{3840,2160}}) do
    local r=Layout.compute(size[1],size[2])
    eq(r.list_font>=10,true); eq(r.list_font<=14,true)
    eq(r.list_title_font,r.list_font+3)
  end
end)
test("header clock font fits the narrow medium identity rail",function()
  local medium=Layout.compute(1000,900); local wide=Layout.compute(1920,1080)
  eq(medium.header_clock_font,10); eq(wide.header_clock_font>=11,true)
  local estimatedLine=23*medium.header_clock_font*.6
  eq(estimatedLine<=medium.left-medium.panel_padding*2,true)
end)
test("component metrics grow without overflowing narrow layouts",function()
  for _,size in ipairs({{760,700},{900,650},{1200,800},{2056,1177},{3840,2160}}) do
    local r=Layout.compute(size[1],size[2]); eq(r.body_font<=22,true); eq(r.heading_font<=28,true); eq(r.panel_padding<=24,true); eq(r.gauge_height<=56,true)
  end
end)

test("content boxes scale with typography instead of clipping",function()
  local compact=Layout.compute(760,700); local wide=Layout.compute(1920,1080)
  eq(wide.title_height>=wide.heading_font+24,true)
  eq(wide.room_height>=wide.heading_font+wide.body_font*6+44,true)
  eq(wide.exit_height>=wide.small_font+12,true)
  eq(wide.identity_height>=wide.heading_font+wide.body_font*6+48,true)
end)

test("new cards derive dimensions from responsive fonts",function()
  for _,size in ipairs({{760,700},{1200,800},{2056,1177},{3840,2160}}) do
    local r=Layout.compute(size[1],size[2]); eq(r.inventory_row_height>=r.inventory_font+8,true); eq(r.details_line_height>=r.body_font+4,true); eq(r.compass_cell>=r.compass_font+10,true); eq(r.utility_height>=r.utility_font+10,true); eq(r.console_width>=math.floor(size[1]*.65),true)
  end
end)
test("combat details stay in the right rail",function()
  eq(Layout.detailsPlacement(240,26,500),"right")
  eq(Layout.detailsPlacement(120,26,300),"right")
end)
test("combat details reserve armor stance roundtime and position rows",function()
  eq(Layout.detailsCardRows(2),5)
  eq(Layout.detailsCardRows(4),5)
end)
test("right rail preserves minimum inventory before showing character details",function()
  eq(Layout.detailsFit(900,400,240,140),true)
  eq(Layout.detailsFit(700,400,240,140),false)
end)
test("right-side vitals stack uses compact readable gauge typography",function()
  local r=Layout.compute(1920,1080)
  eq(r.lower_scale,.8)
  eq(r.lower_title_height,0)
  eq(r.lower_small_font<=r.lower_body_font+1,true)
  eq(r.lower_gauge_height>=r.lower_small_font+12,true)
  for _,pair in ipairs({
    {r.lower_body_font,r.body_font},{r.lower_heading_font,r.heading_font},
    {r.lower_panel_padding,r.panel_padding},{r.lower_row_gap,r.row_gap},
    {r.lower_room_height,r.room_height},{r.lower_compass_cell,r.compass_cell},
    {r.lower_utility_height,r.utility_height}
  }) do eq(pair[1],math.floor(pair[2]*.8+.5)) end
end)
test("embedded mapper is allocated immediately above compass on wide screens",function()
  local r=Layout.compute(1920,1080)
  eq(r.mapper_visible,true); eq(r.lower_mapper_height>=300,true)
  eq(r.lower_mapper_gap,r.lower_row_gap)
end)

test("moving vitals out of the navigation rail increases usable mapper space",function()
  local wide=Layout.compute(1920,1080); local geometry=Layout.lowerPanelGeometry(wide,true,true)
  eq(geometry.show_psi,true); eq(geometry.show_web,true)
  eq(geometry.content_top,wide.lower_panel_padding)
  eq(geometry.mapper_height>=300,true)
  eq(wide.vitals_side,"center")
end)
test("mapper toolbar reserves space above the existing usable map minimum",function()
  for _,size in ipairs({{1920,1080},{1200,800},{1200,650},{1000,650}}) do
    local r=Layout.compute(size[1],size[2]); local geometry=Layout.lowerPanelGeometry(r,false,false)
    eq(r.lower_mapper_toolbar_height>0,true)
    if geometry.mapper_height>0 then eq(geometry.mapper_height-r.lower_mapper_toolbar_height>=r.lower_mapper_min_height,true) end
  end
  local compact=Layout.compute(760,700)
  eq(compact.lower_mapper_toolbar_height,0)
end)
test("configured mapper minimum height affects feasible responsive layouts",function()
  local defaultWide=Layout.compute(1920,1080,nil,{minimum_height=90})
  local customWide=Layout.compute(1920,1080,nil,{minimum_height=180})
  eq(defaultWide.lower_mapper_min_height,140); eq(customWide.lower_mapper_min_height,180)
  eq(customWide.lower_mapper_height>=180,true)
  local customMedium=Layout.compute(1200,800,nil,{minimum_height=130})
  eq(customMedium.lower_mapper_min_height,130); eq(customMedium.lower_mapper_height>=130,true)
  local infeasible=Layout.compute(1200,420,nil,{minimum_height=180})
  local geometry=Layout.lowerPanelGeometry(infeasible,false,false)
  eq(geometry.mapper_height==0 or geometry.mapper_height>=180,true)
end)
test("medium and short windows preserve mapper before optional room detail",function()
  for _,size in ipairs({{1200,800},{1200,650},{1000,650}}) do
    local r=Layout.compute(size[1],size[2])
    eq(r.mapper_visible,true); eq(r.lower_mapper_height>=90,true)
    eq(r.lower_room_visible_height<=r.lower_room_height,true)
  end
end)
test("compact layouts may hide the embedded mapper",function()
  local r=Layout.compute(760,700)
  eq(r.mapper_visible,false); eq(r.lower_mapper_height,0); eq(r.lower_mapper_toolbar_height,0)
end)
test("disabled mapper releases its layout space at every noncompact resolution",function()
  for _,size in ipairs({{1920,1080},{1100,800}}) do
    local r=Layout.compute(size[1],size[2],{}, {enabled=false})
    eq(r.mapper_visible,false); eq(r.lower_mapper_height,0); eq(r.lower_mapper_toolbar_height,0)
  end
end)
test("lower panel reduction preserves location and mapper floors before hiding the mapper",function()
  local wide=Layout.compute(2560,1400); local full=Layout.lowerPanelGeometry(wide,true,true)
  eq(full.optional_count,2); eq(full.room_height,wide.lower_room_height); eq(full.mapper_height>=140,true)
  local medium=Layout.compute(1200,650); local constrained=Layout.lowerPanelGeometry(medium,true,true)
  eq(constrained.optional_count,2)
  eq(constrained.room_height>=medium.lower_room_min_height,true)
  if constrained.mapper_height>0 then eq(constrained.mapper_height>=90,true) end
  local impossible=Layout.compute(1200,420); local reduced=Layout.lowerPanelGeometry(impossible,true,true)
  eq(reduced.mapper_height,0)
  eq(reduced.panel_height<=impossible.window_height-impossible.header_height,true)
end)
test("active roundtime reserves only left navigation rail space",function()
  for _,size in ipairs({{1920,1080},{1200,800},{1000,650}}) do
    local layout=Layout.compute(size[1],size[2]); local ready=Layout.lowerPanelGeometry(layout,false,false,false); local active=Layout.lowerPanelGeometry(layout,false,false,true)
    eq(active.roundtime_visible,true); eq(active.roundtime_height,layout.lower_roundtime_height)
    eq(active.roundtime_y+active.roundtime_height,active.panel_height-layout.lower_panel_padding)
    eq(active.utility_y+active.utility_height+layout.lower_roundtime_gap,active.roundtime_y)
    eq(layout.console_width,size[1]-layout.console_left-layout.console_right)
    eq(layout.bottom,layout.vitals_strip_height+layout.command_line_clearance)
    eq(ready.roundtime_visible,false); eq(ready.utility_y+ready.utility_height,ready.panel_height-layout.lower_panel_padding)
  end
end)
