local History=require("chat_history")

test("deduplicates only identical adjacent entries",function()
  local history=History.new(1000,3)
  local entry={category="ESP",speaker="Tekk",message="hello"}
  eq(history:append(entry,100),true)
  eq(history:append(entry,101),false)
  eq(history:append({category="ESP",speaker="Gia",message="hello"},102),true)
  eq(history:append(entry,103),true)
end)

test("deduplicates only within the inclusive forward time window",function()
  local entry={category="ESP",speaker="Tekk",message="hello"}
  local exact=History.new(10,3)
  eq(exact:append(entry,100),true)
  eq(exact:append(entry,103),false)
  local outside=History.new(10,3)
  eq(outside:append(entry,100),true)
  eq(outside:append(entry,104),true)
  local earlier=History.new(10,3)
  eq(earlier:append(entry,200),true)
  eq(earlier:append(entry,100),true)
end)

test("normalizes every dedupe field while retaining a changed target",function()
  local history=History.new(10,3)
  eq(history:append({category=" esp ",speaker=" Tekk  Prime ",target=" Dace   Alterac ",message=" Hello   there "},100),true)
  eq(history:append({category="ESP",speaker="tekk prime",target="dace alterac",message="hello there"},101),false)
  eq(history:append({category="ESP",speaker="tekk prime",target="Other",message="hello there"},102),true)
  eq(#history:entries("ALL"),2)
end)

test("retains only the newest visible limit",function()
  local history=History.new(2,3)
  history:append({category="ROOM",message="one"},1)
  history:append({category="ROOM",message="two"},2)
  history:append({category="ROOM",message="three"},3)
  eq(#history:entries("ALL"),2)
  eq(history:entries("ALL")[1].message,"two")
end)

test("hard caps an oversized visible limit at the newest thousand",function()
  local history=History.new(1500,3)
  for index=1,1501 do history:append({category="ROOM",message="line-"..index},index) end
  local entries=history:entries("ALL")
  eq(#entries,1000)
  eq(entries[1].message,"line-502")
  eq(entries[1000].message,"line-1501")
end)
test("new sibling history preserves limits without sharing entries",function()
  local first=History.new(2,4); first:append({category="ROOM",message="first"},1); local second=first:newSibling()
  eq(second.limit,2); eq(second.dedupeSeconds,4); eq(#second:entries(),0); eq(#first:entries(),1)
end)

test("hydrates older entries without duplicating overlap or disturbing live order",function()
  local history=History.new(4,3)
  local overlap={schema=1,timestamp="2026-08-31T12:00:00-04:00",character="Dace Alterac",category="ESP",speaker="Tekk",message="overlap",line='Tekk (ESP): "overlap"',source="builtin"}
  history:append(overlap,100)
  history:append({schema=1,timestamp="2026-08-31T13:00:00-04:00",character="Unknown",category="QUEST",message="live",line="live",source="custom"},104)
  history:hydrate({
    {schema=1,timestamp="2026-08-31T11:00:00-04:00",character="Dace Alterac",category="ROOM",speaker="Gia",message="older",line='Gia says, "older"',source="builtin"},
    overlap,
  })
  local entries=history:entries("ALL")
  eq(#entries,3)
  eq(entries[1].message,"older")
  eq(entries[2].message,"overlap")
  eq(entries[3].message,"live")
  eq(table.concat(history:categories(),","),"ROOM,ESP,QUEST")
end)

test("filters private categories and preserves category insertion order",function()
  local history=History.new(10,3)
  history:append({category="ROOM",message="room"},1)
  history:append({category="WHISPER",message="whisper"},2)
  history:append({category="ESP",message="esp"},3)
  history:append({category="DRAGON",message="dragon"},4)
  history:append({category="SECIAN",message="secian"},5)
  history:append({category="CONTACT",message="contact"},6)
  history:append({category="STAFF",message="staff"},7)
  eq(#history:entries("PRIVATE"),5)
  eq(history:entries("PRIVATE")[1].message,"whisper")
  local categories=history:categories()
  eq(categories[1],"ROOM")
  eq(categories[7],"STAFF")
end)

test("room filter includes both nearby speakers and the active character",function()
  local history=History.new(10,3)
  history:append({category="ROOM",message="Gia asks Dace"},1)
  history:append({category="OWN",message="Dace answers Gia"},2)
  history:append({category="ESP",message="remote"},3)
  local entries=history:entries("ROOM")
  eq(#entries,2); eq(entries[1].category,"ROOM"); eq(entries[2].category,"OWN")
  eq(#history:entries("PRIVATE"),1)
end)
