local Roundtime=require("roundtime")
local function tracker()
  local now=100
  local rt=Roundtime.new(function() return now end)
  return rt,function(value) now=value end
end
test("roundtime adds distinct printed double claws and fumble penalties",function()
  for _,pair in ipairs({{7,7},{4,4},{3,2},{3,4},{5,2},{5,4},{7,2},{7,4}}) do
    local rt=tracker(); eq(rt:text(pair[1]),pair[1]); eq(rt:text(pair[2]),pair[1]+pair[2])
  end
end)
test("roundtime reconciles text before GMCP without charging twice",function()
  local rt=tracker(); rt:gmcp(0); eq(rt:text(7),7); eq(rt:gmcp(7),7)
  eq(rt:text(2),9); eq(rt:gmcp(9),9)
end)
test("roundtime reconciles GMCP before printed delays without charging twice",function()
  local rt=tracker(); eq(rt:gmcp(9),9); eq(rt:text(7),9); eq(rt:text(2),9)
end)
test("roundtime reconciles interleaved base and penalty snapshots",function()
  local rt=tracker(); eq(rt:text(7),7); eq(rt:gmcp(9),9); eq(rt:text(2),9)
end)
test("unchanged cached GMCP cannot restart the countdown after expiry",function()
  local rt,clock=tracker(); rt:gmcp(3); clock(101); eq(rt:gmcp(3),2)
  clock(104); eq(rt:gmcp(3),0); eq(rt:gmcp(nil),0)
end)
test("unrelated missing or invalid roundtime leaves the deadline alone",function()
  local rt=tracker(); rt:text(7)
  for _,bad in ipairs({"bad",-1,math.huge,0/0,86401}) do eq(rt:gmcp(bad),7); eq(rt:text(bad),7) end
  eq(rt:gmcp(nil),7)
end)
test("stale shorter snapshots within the text burst do not erase fumble penalties",function()
  local rt=tracker(); rt:text(7); rt:text(2); eq(rt:gmcp(7),9)
end)
test("fresh GMCP remaining time is authoritative after the output burst",function()
  local rt,clock=tracker(); rt:text(7); rt:text(2); clock(102); eq(rt:gmcp(3),3)
  eq(rt:gmcp(0),0)
end)
test("positive snapshots followed by their text are deduplicated during existing RT",function()
  local rt,clock=tracker(); rt:gmcp(3); clock(101); eq(rt:gmcp(5),5); eq(rt:text(5),5)
end)
test("roundtime accounts for time elapsed between delays and late timers",function()
  local rt,clock=tracker(); rt:text(7); clock(102); eq(rt:text(2),7)
  clock(108); eq(rt:tick(),1); clock(111); eq(rt:tick(),0)
end)
test("roundtime resets source credits between characters",function()
  local rt=tracker(); rt:gmcp(7); rt:reset(); eq(rt:display(),0)
  eq(rt:text(7),7); eq(rt:gmcp(7),7)
end)
test("clock reads just before a tick cannot expire roundtime one second early",function()
  for _,start in ipairs({100,100.25}) do
    local rt,clock=tracker(); clock(start); rt:text(7)
    clock(start+6); eq(rt:gmcp(nil),1); eq(rt:tick(),1)
    clock(start+7); eq(rt:tick(),0)
  end
end)
test("interleaved snapshots retain unconsumed double claw and fumble credit",function()
  for _,pair in ipairs({{7,7},{7,2},{7,4}}) do
    local rt=tracker(); local total=pair[1]+pair[2]
    rt:gmcp(total); rt:text(pair[1]); rt:gmcp(pair[1])
    eq(rt:text(pair[2]),total)
  end
  local rt=tracker(); rt:gmcp(7); rt:text(3); rt:gmcp(9)
  eq(rt:text(4),9); eq(rt:text(2),9)
end)
test("update handoff preserves an expired snapshot and elapsed active deadline",function()
  local old,clock=tracker(); old:gmcp(7); clock(102)
  local fresh,newClock=tracker(); newClock(103); assert(fresh:restore(old:handoff()))
  eq(fresh:display(),4); eq(fresh:gmcp(7),4)
  newClock(108)
  local actual,nextClock=tracker(); nextClock(108); assert(actual:restore(fresh:handoff()))
  eq(actual:display(),0); eq(actual:gmcp(7),0)
end)
test("invalid roundtime handoffs do not mutate the current countdown",function()
  local rt=tracker(); rt:text(5)
  for _,snapshot in ipairs({{}, {schema=2,deadline=101}, {schema=1,deadline=math.huge},
      {schema=1,deadline=-1}, {schema=1,deadline=101,last_gmcp="bad"}}) do
    eq(rt:restore(snapshot),false); eq(rt:display(),5)
  end
end)
test("an immediate reload preserves unconsumed snapshot credit and text correlation",function()
  for _,pair in ipairs({{7,7},{7,2},{7,4}}) do
    local old=tracker(); old:gmcp(pair[1]+pair[2]); old:text(pair[1])
    local fresh=tracker(); assert(fresh:restore(old:handoff()))
    eq(fresh:text(pair[2]),pair[1]+pair[2])
  end
  local old=tracker(); old:text(7); old:text(2)
  local fresh=tracker(); assert(fresh:restore(old:handoff()))
  eq(fresh:gmcp(7),9)
end)
test("handoff rejects invalid reconciliation timestamps and credits",function()
  local rt=tracker(); rt:text(5)
  for _,snapshot in ipairs({{schema=1,deadline=107,credit=-1}, {schema=1,deadline=107,credit=7},
      {schema=1,deadline=107,credit_at=math.huge}, {schema=1,deadline=107,text_at=0/0},
      {schema=1,deadline=107,text_at=102}}) do
    eq(rt:restore(snapshot),false); eq(rt:display(),5)
  end
end)

-- DELAY reports the current total remaining time, independently of the
-- additive printed-delay and GMCP reconciliation paths.
test("DELAY sync repeats replace the total instead of adding or using a cache",function()
  local rt,clock=tracker()
  eq(rt:sync(6),6); eq(rt.deadline,106)
  eq(rt:sync(6),6); eq(rt.deadline,106)
  clock(102)
  eq(rt:sync(6),6); eq(rt.deadline,108)
  clock(103); eq(rt:display(),5)
end)
test("DELAY sync can shrink or grow an active deadline",function()
  local rt,clock=tracker(); rt:text(9)
  eq(rt:sync(6),6); eq(rt.deadline,106)
  eq(rt:sync(12),12); eq(rt.deadline,112)
  clock(102.25)
  eq(rt:sync(3),3); eq(rt.deadline,105.25)
  eq(rt:sync(8),8); eq(rt.deadline,110.25)
end)
test("DELAY sync accepts bounded remaining durations without losing fractions",function()
  local rt,clock=tracker(); clock(100.25)
  eq(rt:sync(86400),86400); eq(rt.deadline,86500.25)
  eq(rt:sync(2.5),3); eq(rt.deadline,102.75)
  clock(100.75); eq(rt:remaining(),2); eq(rt:display(),2)
  eq(rt:sync("6"),6); eq(rt.deadline,106.75)
end)
test("DELAY sync zero clears the countdown without letting cached GMCP restart it",function()
  local rt,clock=tracker(); rt:gmcp(9); rt:text(7)
  eq(rt:sync(0),0); eq(rt.deadline,100)
  eq(rt.last_gmcp,9); eq(rt:gmcp(9),0)
  clock(101); eq(rt:tick(),0); eq(rt:gmcp(9),0)
  eq(rt:text(2),2)
end)
test("DELAY sync corrects a nine second text burst to six before the next delay",function()
  local rt=tracker(); rt:text(7); eq(rt:text(2),9)
  eq(rt:gmcp(7),9)
  eq(rt:sync(6),6); eq(rt:display(),6); eq(rt.deadline,106)
  eq(rt:gmcp(7),6); eq(rt.deadline,106)
  eq(rt:text(2),8); eq(rt.deadline,108)
  eq(rt:gmcp(7),8)
end)
test("DELAY sync preserves the GMCP marker for longer shorter and zero cached values",function()
  for _,cached in ipairs({7,3,0}) do
    local rt,clock=tracker(); rt:gmcp(cached)
    eq(rt:sync(6),6); eq(rt.last_gmcp,cached)
    clock(100.25); eq(rt:gmcp(cached),6); eq(rt.deadline,106)
    clock(102); eq(rt:gmcp(cached),4); eq(rt.deadline,106)
    clock(107); eq(rt:gmcp(cached),0); eq(rt.deadline,106)
  end
end)
test("DELAY sync discards unconsumed GMCP credit so a new printed delay adds fully",function()
  for _,printed in ipairs({0,7}) do
    local rt=tracker(); rt:gmcp(9)
    if printed>0 then rt:text(printed) end
    eq(rt:sync(6),6); eq(rt.last_gmcp,9)
    eq(rt:gmcp(9),6)
    eq(rt:text(2),8); eq(rt:text(2),10)
  end
end)
test("DELAY sync clears source correlation timestamps as well as their credit",function()
  for _,value in ipairs({6,0}) do
    local rt=tracker(); rt:gmcp(9); rt:text(7)
    local before=rt:handoff()
    eq(before.credit,2); eq(before.credit_at,100); eq(before.text_at,100)
    rt:sync(value)
    local after=rt:handoff()
    eq(after.deadline,100+value); eq(after.last_gmcp,9)
    eq(after.credit or 0,0); eq(after.credit_at,nil); eq(after.text_at,nil)
  end
end)
test("DELAY sync uses elapsed time and does not expire early after a clock read",function()
  for _,start in ipairs({100,100.25}) do
    local rt,clock=tracker(); clock(start); rt:sync(7)
    clock(start+6); eq(rt:gmcp(nil),1); eq(rt:tick(),1)
    clock(start+7); eq(rt:tick(),0)
  end
  local rt,clock=tracker(); rt:text(9)
  clock(101); eq(rt:tick(),8)
  clock(101.25); eq(rt:sync(6),6); eq(rt.deadline,107.25)
  clock(102); eq(rt:tick(),6)
  clock(106.75); eq(rt:display(),1); eq(rt:tick(),1)
  clock(107.25); eq(rt:tick(),0)
end)
test("DELAY sync retains timer progress when the clock is coarse",function()
  local rt=tracker(); eq(rt:sync(3),3)
  eq(rt:tick(),2); eq(rt:tick(),1); eq(rt:tick(),0)
  eq(rt:sync(4),4); eq(rt.deadline,107)
  eq(rt:tick(),3); eq(rt:tick(),2); eq(rt:tick(),1); eq(rt:tick(),0)
end)
test("invalid DELAY sync input leaves the deadline marker and reconciliation state alone",function()
  local rt=tracker(); rt:gmcp(7); rt:text(3)
  local before=rt:handoff()
  for _,bad in ipairs({{}, {value="bad"}, {value=""}, {value="6 seconds"},
      {value=-1}, {value=86401}, {value=86400.01}, {value=math.huge},
      {value=-math.huge}, {value=0/0}, {value=false}, {value=true},
      {value={}}, {value=function() return 6 end}}) do
    eq(rt:sync(bad.value),7)
    local after=rt:handoff()
    for _,key in ipairs({"schema","deadline","last_gmcp","credit","credit_at","text_at"}) do
      eq(after[key],before[key])
    end
  end
  eq(rt:text(2),7)
end)
test("update handoff preserves a corrected deadline and its cached GMCP marker after expiry",function()
  local old=tracker(); old:gmcp(7); old:text(7); old:text(2); old:sync(6)
  local snapshot=old:handoff()
  eq(snapshot.deadline,106); eq(snapshot.last_gmcp,7)
  local fresh,newClock=tracker(); newClock(103); assert(fresh:restore(snapshot))
  eq(fresh.deadline,106); eq(fresh:display(),3); eq(fresh:gmcp(7),3)
  newClock(107)
  local actual,nextClock=tracker(); nextClock(107); assert(actual:restore(fresh:handoff()))
  eq(actual.deadline,106); eq(actual:display(),0); eq(actual:gmcp(7),0)
end)
test("immediate handoff after DELAY sync keeps new delays additive and zero cleared",function()
  for _,value in ipairs({6,0}) do
    local old=tracker(); old:gmcp(9); old:text(7); old:sync(value)
    local fresh=tracker(); assert(fresh:restore(old:handoff()))
    eq(fresh.deadline,100+value); eq(fresh:display(),value); eq(fresh:gmcp(9),value)
    eq(fresh:text(2),value+2)
  end
end)
