local Clock=require("game_clock")

test("game clock advances at configured two-times speed",function()
  local clock=Clock.new({speed=2,sunrise_hour=6,sunset_hour=18},function() return 100 end)
  clock:sync({hour=3,minute=22,day=4,month=8,year=362},100)
  local value=clock:current(130)
  eq(value.hour,3); eq(value.minute,23); eq(value.period,"Night")
end)
test("game clock rolls a twelve-month thirty-day calendar into the next year",function()
  local clock=Clock.new({speed=2},function() return 0 end); clock:sync({hour=23,minute=59,day=30,month=12,year=362},0)
  local value=clock:current(30); eq(value.hour,0); eq(value.minute,0); eq(value.day,1); eq(value.month,1); eq(value.year,363)
end)
test("game clock adopts the named six-month sixty-day calendar",function()
  local clock=Clock.new({speed=2},function() return 0 end); clock:sync({hour=23,minute=59,day=60,month=6,year=362,days_per_month=60,months_per_year=6},0)
  local value=clock:current(30); eq(value.hour,0); eq(value.minute,0); eq(value.day,1); eq(value.month,1); eq(value.year,363)
end)

test("game clock handles noon midnight and calendar rollover",function()
  local clock=Clock.new({speed=2,sunrise_hour=6,sunset_hour=18},function() return 0 end)
  clock:sync({hour=17,minute=59,day=4,month=8,year=362},0)
  eq(clock:current(30).period,"Night")
  clock:sync({hour=5,minute=59,day=4,month=8,year=362},0)
  eq(clock:current(30).period,"Daytime")
  clock:sync({hour=23,minute=59,day=4,month=8,year=362},0)
  local value=clock:current(30); eq(value.hour,0); eq(value.minute,0); eq(value.day,5)
end)

test("game clock resynchronization corrects drift",function()
  local clock=Clock.new({speed=2},function() return 100 end)
  clock:sync({hour=3,minute=22,day=4,month=8,year=362},100)
  eq(clock:current(160).minute,24)
  clock:sync({hour=3,minute=23,day=4,month=8,year=362},160)
  eq(clock:current(190).minute,24)
end)
