return {
  schema = 1,
  edition = "staff",
  package_name = "DragonsGateHUD",
  version = "0.2.163",
  layout = { left_width = 190, right_width = 270, min_console_width = 520 },
  chat = { enabled=true, height_percent=.21, target_height=240, min_height=160, max_height=320, visible_limit=1000, dedupe_seconds=3, timestamps=true },
  colorization = {
    enabled=true,
    room_enabled=true,
    exits_enabled=true,
    currency_enabled=true,
    races_enabled=true,
    classes_enabled=true,
    highlights_enabled=true,
    portal_enabled=true,
    attack_enabled=true,
    damage_enabled=true,
    danger_enabled=true,
    recovery_enabled=true,
    upkeep_enabled=true,
    spell_enabled=true,
    discovery_enabled=true,
    illumination_enabled=true,
    room_color={224,184,79},
    label_color={139,45,45},
    direction_color={191,91,33},
    gold_color={224,184,79},
    silver_color={192,192,192},
    portal_color={55,190,200},
    attack_color={205,62,62},
    damage_color={255,70,70},
    danger_color={205,135,45},
    recovery_color={90,165,105},
    upkeep_color={185,105,45},
    spell_color={145,95,190},
    discovery_color={225,185,70},
    illumination_color={220,200,85},
    darkness_color={105,120,140},
  },
  time = { speed=2, sunrise_hour=6, sunset_hour=18 },
  roller = {
    target_total=53, hard_stop=62, max_rolls=nil, reroll_delay=.1, reroll_command="n",
    auto_start_on_name=true, use_min_stats=true, require_min_stats_to_stop=true,
    show_every_roll=true, logging_enabled=true, log_folder="og_dg_roller", master_file="og_dg_rolls_master.txt",
    min_stats={STR=5,INT=5,WIS=5,DEX=5,AGI=5,CON=5,CHA=5,WIL=5,VOI=5,PER=5,APP=5},
  },
  mapper = {
    enabled=true,
    walk_timeout=12,
    minimum_height=90,
    height_percent=.40,
    maximum_height=380,
    schema=1,
    special_timeout = 12,
    special_patterns = {},
    transition_submaps = {gate=true,portal=true,door=true,arch=true,path=true,other=true},
    zoom_step = 2.5,
    zoom_min = 3.0,
    zoom_max = 60.0,
  },
  theme = { background="#080b0a", panel="#0d1210", border="#423825", text="#d7d0bf", muted="#75857c", accent="#e0b56c", jade="#79b386", gold="#e0b84f", silver="#c0c0c0", hp="#ba5147", fatigue="#b08f18" },
  panels = { character=true, vitals=true, room=true, currency=true },
  github = { owner="wizzydizzy-ctrl", repository="dragons-gate-staff-hud", channel="stable" },
  update = { auto_check=false, auto_apply=false, timeout_seconds=30, manifest_limit=65536, package_limit=10485760 }
}
